core/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required

import core.views
from core.widgets import AuthSelect2View
import sms.views

urlpatterns = [
    re_path(r'^$', login_required(core.views.ManagementView.as_view()), name='core_management'),
    re_path(r'^metrics/$', login_required(core.views.MetricsView.as_view()), name='core_management_metrics'),
    re_path(r'^nps/$', login_required(core.views.NPSView.as_view()), name='core_management_nps'),
    re_path(r'^charts/membership/$', login_required(core.views.MembershipRateChartView.as_view()), name='core_management_membership_rate'),
    re_path(r'^charts/calls/$', login_required(core.views.CallRateChartView.as_view()), name='core_management_call_rate'),
    re_path(r'^bulk_sms/$', login_required(sms.views.CustomerFilterFormView.as_view()), name='core_management_customer_filter'),
    re_path(r'^bulk_sms/compose/$', login_required(sms.views.BulkOutgoingSMSCreateView.as_view()), name='core_management_customer_bulk_compose'),
    re_path(r'^new_customers_chart/', login_required(core.views.new_customers_chart), name='new_customers_chart'),
    re_path(r'^nps_histogram_chart/', login_required(core.views.nps_histogram_chart), name='nps_histogram_chart'),
    re_path(r'^task_metrics_chart/', login_required(core.views.task_metrics_chart), name='task_metrics_chart'),
    re_path(r'^select2/', login_required(core.widgets.AuthSelect2View.as_view()), name='auth_select2_view'),
]

exports/urls.py
from django.conf import re_path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'exports'

urlpatterns = [
    re_path(r'^$', login_required(views.ExportView.as_view()), name='list'),
    re_path(r'^customers/', login_required(views.CustomerExportCreateView.as_view()), name='customers'),
    re_path(r'^incoming-messages/', login_required(views.IncomingSMSExportCreateView.as_view()), name='incoming-messages'),
    re_path('^maps/$', login_required(views.MapExportView.as_view()), name='maps_list'),
    re_path(r'^maps/create/$', login_required(views.MapExportCreateView.as_view()), name='maps_create'),
]

exports/models.py
from random import SystemRandom

from django.core.files.storage import default_storage
from django.db import models
import heatmap as hm
from ishamba.settings import MEDIA_ROOT

from datetime import timedelta

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _

from model_utils import Choices


def media_root_fn(*args, **kwargs):
    """ being used to avoid creating migrations on every computer that runs this project"""
    return settings.MEDIA_ROOT


class BaseExport(models.Model):
    """ Abstract model for storing exports of other data models.
    """
    # constants
    STATUS = Choices(
        (0, 'failed', _('Failed')),
        (1, 'queued', _('Queued')),
        (2, 'started', _('Started')),
        (3, 'complete', _('Complete')),
    )

    # export QuerySet fields
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.SET_NULL,
                                     verbose_name=_('Export type'),
                                     null=True)
    filters = models.JSONField(default=dict)
    fields = models.JSONField(default=dict)

    # record keeping fields
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   on_delete=models.SET_NULL,
                                   null=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    started_at = models.DateTimeField(_("Started at"), null=True, blank=True)
    completed_at = models.DateTimeField(_("Completed at"),
                                        null=True,
                                        blank=True)
    status = models.PositiveSmallIntegerField(_("Status"),
                                              choices=STATUS,
                                              default=STATUS.queued)

    exported_file = models.FilePathField(
        path=media_root_fn,
        max_length=256,
        match=r'.csv$',
        blank=True
    )

    class Meta:
        abstract = True

    @property
    def duration(self):
        """ The duration of the export, if it is complete, otherwise None.
        """
        if self.started_at and self.completed_at:
            return timedelta(self.started_at, self.completed_at)

    @property
    def url(self):
        if not self.exported_file:
            return None

        return default_storage.url(self.exported_file)

    @property
    def export_queryset(self):
        """ Builds a `QuerySet` object from `self.content_type`,
        `self.filters`, and `self.fields`.
        """
        model = self.content_type.model_class()

        return (model._default_manager.filter(**self.filters)
                                      .values(*self.fields['fields'])
                                      .distinct())

    def export_sql_with_params(self):
        """ Generates a custom SQL query that uses the SQL generated by
        `self.export_queryset` to STDOUT.
        """
        qs_query, params = self.export_queryset.query.sql_with_params()

        query = "COPY ({query}) TO STDOUT DELIMITER ',' CSV HEADER".format(
            query=qs_query
        )

        return query, params

    def generate_filename(self):
        """ Generates a new random filename for the `Export.exported_file`.
        """
        return '{:032x}.csv'.format(SystemRandom().getrandbits(256))


class MapExport(BaseExport):

    map_file = models.FilePathField(
        path=media_root_fn,
        max_length=256,
        match=r'.png$',
        blank=True
    )

    @property
    def url(self):
        if not self.map_file:
            return None

        return default_storage.url(self.map_file)

    @property
    def export_queryset(self):
        """ Builds a `QuerySet` object from `self.content_type`,
        `self.filters`, and `self.fields`.
        """
        model = self.content_type.model_class()

        return (model._default_manager.filter(**self.filters)
                                      .only(*self.fields['fields'])
                                      .distinct())

    def get_points(self):
        for c in self.export_queryset.iterator():
            latlng = c.location
            if not latlng:
                continue
            yield hm.Point(hm.LatLon(latlng.y, latlng.x))

    def get_map_config(self):
        """
        Return the map render settings
        """
        kernel = hm.LinearKernel(10)  # Radius of points in pixels (int)
        colors = hm.ColorMap(
            hsva_min=hm.ColorMap.str_to_hsva('02affff00'),
            hsva_max=hm.ColorMap.str_to_hsva('000ffffff')
        )
        config = hm.Configuration()
        config.osm = True  # Use an OSM background
        config.zoom = 6  # OSM zoom level
        config.kernel = kernel
        config.colormap = colors
        config.margin = 20  # Buffer around edge of map in pixels (int)
        return config

    def make_map_image(self, config):
        config.shapes = self.get_points()
        config.fill_missing()
        matrix = hm.process_shapes(config).finalized()
        return hm.ImageMaker(config).make_image(matrix)

    def generate_filename(self):
        return '{:032x}.png'.format(SystemRandom().getrandbits(256))


class Export(BaseExport):
    """
    Define a concrete export class. This class and its associated DB table
    and migrations used to be in the mediae_crm repo. Rather than change the
    table names, we now point this class to that existing table.
    """
    class Meta:
        db_table = "mcrm_exports_export"

exports/forms.py
from django import forms

from .form_helpers import FieldSelectionFormHelper


class FieldSelectionForm(forms.Form):

    fields = forms.MultipleChoiceField(choices=[],
                                       widget=forms.CheckboxSelectMultiple(),
                                       label='')

    helper = FieldSelectionFormHelper()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fields'].choices = self.EXPORTED_FIELD_CHOICES


class CustomerFieldSelectionForm(FieldSelectionForm):

    EXPORTED_FIELD_CHOICES = (
        ('name', 'Name'),
        ('sex', 'Sex'),
        ('dob', 'Date of birth'),
        ('phones__number', 'Phone number'),
        ('county__name', 'County'),
        ('postal_address', 'Postal address'),
        ('postal_code', 'Postal code'),
    )


class IncomingSMSFieldSelectionForm(FieldSelectionForm):

    EXPORTED_FIELD_CHOICES = (
        ('task__id', 'Task ID'),
        ('at', 'Time received'),
        ('sender', 'Phone number'),
        ('text', 'Message text'),
        ('customer__sex', 'Customer sex'),
    )

exports/views.py
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django_tables2 import SingleTableView

from exports.models import Export, MapExport
from taggit.utils import _parse_tags

from customers.models import Customer
from sms.models import IncomingSMS

from .filters import CustomerExportFilter, IncomingSMSExportFilter
from .forms import CustomerFieldSelectionForm, IncomingSMSFieldSelectionForm
from .tables import ExportTable
from .tasks import generate_export, generate_map


class BaseExportCreateView(TemplateView):
    """ Base view for creating exports.
    """

    http_method_names = ['get', 'post']

    filter_form = None
    field_selection_form = None
    model = None
    export_model = Export
    export_task = generate_export

    def get_filter_form_kwargs(self):
        kwargs = {
            'queryset': self.model.objects.all()
        }
        if self.request.method.lower() == "post":
            kwargs['data'] = self.request.POST

        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            **kwargs)

        context['filter'] = self.filter

        context['field_selection_form'] = self.field_selection_form(
            initial={'fields': self.DEFAULT_EXPORTED_FIELDS}
        )

        return context

    def dispatch(self, request, *args, **kwargs):
        self.filter = self.filter_form(**self.get_filter_form_kwargs())
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        if self.filter.is_bound and self.filter.form.is_valid():
            self.create_export(
                self.process_filter_data(self.filter.form.cleaned_data))
            return HttpResponseRedirect(self.success_url)
        else:
            return self.render_to_response(context)

    def process_filter_data(self, cleaned_data):
        """ Due to implementation specifics tag filters need to be
        pre-processed before using them as filters.
        """
        processed = {}

        for field_name, value in cleaned_data.items():
            if 'tag' in field_name:
                value = _parse_tags(value)
            processed[field_name] = value

        return processed

    def create_export(self, filters):
        """ Creates a new Export instance using filters specified via the
        filter form and starts the `generate_export` Celery task.
        """
        # any key that is in complete_record_filters will be included in the
        # filter even if it equates to false (like an empty string)
        complete_record_filters = getattr(self.filter.form,
                                          'complete_record_filters', {})

        export_filters = {}
        for key, val in filters.items():
            if val or (key in complete_record_filters):
                export_filters[key] = val

        export = self.export_model.objects.create(
            content_type=ContentType.objects.get_for_model(self.model),
            filters=export_filters,
            fields={'fields': list(self.get_exported_fields())},
            created_by=self.request.user
        )
        self.export_task.delay(export.pk, self.request.tenant.schema_name)

    def get_exported_fields(self):
        field_selection_form = self.field_selection_form(self.request.POST)
        if field_selection_form.is_valid():
            return field_selection_form.cleaned_data['fields']

        return self.DEFAULT_EXPORTED_FIELDS


class ExportView(SingleTableView):
    model = Export
    table_class = ExportTable
    template_name = 'exports/export_list.html'


class CustomerExportCreateView(BaseExportCreateView):
    """ Handles the generation of Customer exports. Currently the exported
    fields are hard-coded, however, this is to change in the future.
    """
    # TODO: FIX ME (support multiple phones)
    filter_form = CustomerExportFilter
    field_selection_form = CustomerFieldSelectionForm
    model = Customer
    DEFAULT_EXPORTED_FIELDS = ('name', 'sex', 'dob', 'phones__number',
                               'county__name', 'postal_address', 'postal_code')

    template_name = 'exports/customer_export.html'
    success_url = reverse_lazy('exports:list')


class IncomingSMSExportCreateView(BaseExportCreateView):
    filter_form = IncomingSMSExportFilter
    field_selection_form = IncomingSMSFieldSelectionForm
    model = IncomingSMS
    DEFAULT_EXPORTED_FIELDS = ('task__id', 'at', 'sender', 'text')

    template_name = 'exports/incomingsms_export.html'
    success_url = reverse_lazy('exports:list')


class MapExportView(SingleTableView):
    model = MapExport
    table_class = ExportTable
    template_name = 'exports/map_list.html'


class MapExportCreateView(BaseExportCreateView):
    # TODO: FIX ME (support multiple phones)
    filter_form = CustomerExportFilter
    field_selection_form = CustomerFieldSelectionForm
    model = Customer
    export_model = MapExport
    export_task = generate_map
    DEFAULT_EXPORTED_FIELDS = ('name', 'county__name', 'village', 'ward')

    template_name = 'exports/maps_export.html'
    success_url = reverse_lazy('exports:maps_list')

exports/templates/exports/customer_export.html
{% extends 'exports/exports_form.html' %}

{% load link_tags %}

{% block title %}Export Customers{% endblock %}

{% block page_title %}Export Customers{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumb_entry text='Export Customers' url_name='exports:customers' %}
{% endblock %}

exports/templates/exports/download_btn.html
{% with record.url as url %}
    {% if url %}
        <a href="{{ url }}" title="download">
            <i class="fa-solid fa-download-alt"></i>
        </a>
    {% endif %}
{% endwith %}

exports/templates/exports/export_list.html
{% extends 'exports/exports_base.html' %}

{% load crispy_forms_tags %}
{% load django_tables2 %}
{% load static %}

{% block title %}Exports{% endblock %}

{% block page_title %}Exports{% endblock %}

{% block page_content %}
    <div class="bottom-buffer">
        <a class="btn btn-primary" href="{% url 'exports:customers' %}">
            Export customers
        </a>
        <a class="btn btn-primary" href="{% url 'exports:incoming-messages' %}">
            Export incoming messages
        </a>
        <a class="btn btn-primary" href="{% url 'exports:maps_list' %}">
            Maps
        </a>
    </div>

    {# Exports table #}
    <div class="card">
        <div class="card-content">
            {% render_table table %}
        </div>
    </div>
{% endblock %}

exports/templates/exports/exports_base.html
{% extends "base.html" %}

{% load link_tags %}

{% block nav %}
    {% with app_name='exports' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block breadcrumb %}
    {% breadcrumb_entry text='Exports' url_name='exports:list' %}
{% endblock %}

{% block content %}
    <div class='left'>
        {% block submenu %}{% endblock %}
    </div>
    <div class='right'>
        <h2>{% block page_title %}{% endblock %}</h2>
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

exports/templates/exports/exports_form.html
{% extends 'exports/exports_base.html' %}

{% load crispy_forms_tags %}

{% block page_content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                {% crispy filter.form %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                {% crispy field_selection_form %}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

exports/templates/exports/incomingsms_export.html
{% extends 'exports/exports_form.html' %}

{% load link_tags %}

{% block title %}Export Incoming Messages{% endblock %}

{% block page_title %}Export Incoming Messages{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumb_entry text='Export Incoming Messages' url_name='exports:incoming-messages' %}
{% endblock %}

exports/templates/exports/map_list.html
{% extends 'exports/exports_base.html' %}

{% load crispy_forms_tags %}
{% load django_tables2 %}
{% load link_tags %}
{% load static %}

{% block title %}Maps{% endblock %}

{% block page_title %}Maps{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumb_entry text='Maps' url_name='exports:maps_list' %}
{% endblock %}

{% block page_content %}
    <div class="bottom-buffer">
        <a class="btn btn-primary" href="{% url 'exports:maps_create' %}">
            Add map
        </a>
    </div>

    {# Exports table #}
    <div class="card">
        <div class="card-content">
            {% render_table table %}
        </div>
    </div>
{% endblock %}

exports/templates/exports/maps_export.html
{% extends 'exports/exports_form.html' %}

{% load crispy_forms_tags link_tags %}

{% block title %}Export Maps{% endblock %}

{% block page_title %}Export Maps{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumb_entry text='Export Maps' url_name='exports:maps_create' %}
{% endblock %}

exports/templates/exports/user_chip.html
{% load gravatar %}

<div class="chip">
    <span class="assignee-chip">
        {{ record.created_by.email|gravatar }}
        {{ record.created_by }}
    </span>
</div>